### ISSUE TITLE
Scanning for dependencies fail when building using docker BUILDKIT

### ISSUE THREAD

**Issue by mnltejaswini** [Azure/acr-builder#574]
**Describe the bug**
When building with DOCKER_BUILDKIT=1, the build fails to scan dependencies with the following error 
```
failed to query digests, msg:
Error: No such object: mcr.microsoft.com/dotnet/sdk:3.1
: exit status 1
```

**To Reproduce**
1. create a simple Dockerfile 
Sample Dockerfile
```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:3.1
```

2. create a task file to build that docker file with BUILDKIT enabled 
```yaml
version: v1.1.0
steps:
  - id: build
    build: -t $Registry/test:$ID -f Dockerfile .
    env: ["DOCKER_BUILDKIT=1"]
```

3. The build fails to scan dependencies.
```failed to query digests, msg:
Error: No such object: mcr.microsoft.com/dotnet/sdk:3.1
: exit status 1 
```

**Expected behavior**
The build should be success and provide dependencies.
**Screenshots**

**Any relevant environment information**
 - OS: Linux Platform builds
 
This is related to an existing issue in scanning dependencies when build cache is enabled #522

**Comment by shahzzzam** [comment]
Fixed by #580

**Comment by jmsalvo** [comment]
Has this fix been deployed?  I'm still seeing this issue when building using docker BUILDKIT.

**Comment by shahzzzam** [comment]
Its been fixed but not deployed, Sorry for the confusion. Re-opened the issue

**Comment by jmsalvo** [comment]
Thank you for the update

**Comment by northtyphoon** [comment]
The fix has been deployed.
